# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/aqzhang/Vivado_Projs/fir_attempt/fir_attempt.cache/wt [current_project]
set_property parent.project_path /home/aqzhang/Vivado_Projs/fir_attempt/fir_attempt.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/aqzhang/Vivado_Projs/ip_repo/fir_attempt_1.0 [current_project]
read_verilog -library xil_defaultlib {
  /home/aqzhang/Vivado_Projs/fir_attempt/fir_attempt.srcs/sources_1/new/mac_element.v
  /home/aqzhang/Vivado_Projs/fir_attempt/fir_attempt.srcs/sources_1/new/fir_shifter_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top fir_shifter_top -part xc7z020clg484-1


write_checkpoint -force -noxdef fir_shifter_top.dcp

catch { report_utilization -file fir_shifter_top_utilization_synth.rpt -pb fir_shifter_top_utilization_synth.pb }
